### ISSUE TITLE
[Bug Report] Duplicate icon in dock

### ISSUE THREAD

**Issue by sal65535** [cstayyab/WALC#102]
**Describe the bug**
When I open a WALC window a new icon appears in the dock

**WALC Installation Type:** Snap

**Expected behavior**
I expect that when I open a new window, only an indicator under the icon in the dock appears.

**Did you try closing and then opening it back?:** Yes

**Screenshots**
![Walc_Bug](https://user-images.githubusercontent.com/38191926/103490290-2a8e8980-4e1b-11eb-8f39-c43727f40024.png)

**System Information (please complete the following information):**
 - OS/Distro: Ubuntu 20.04

**Additional context**
Plank Dock

**Comment by Zzombiee2361** [comment]
Is WALC icon pinned? Try to unpin and pin it again

**Comment by cstayyab** [comment]
Plank Dock doesn't Support Tray Icon that's why it is being shown there. Pretty much Duplicate of #17 as Elementary OS also uses Plank Dock
