### ISSUE TITLE
[Bug Report] Weird font render when opening system file explorer [nautilus]

### ISSUE THREAD

**Issue by SanpuiRonak** [cstayyab/WALC#107]
**Description**
Weird font render when opening system file explorer [nautilus]

**WALC Installation Type:** Snap

**To Reproduce**
1. Install app on manjaro in snap packaging
2. open (and login) in WALC
3. Try to attach or download any media
4. nautilus comes up with wierd font render

**Expected behavior**
nautilus to come up with proper text.

**Did you try closing and then opening it back?:** Yes

**Screenshots**
![image](https://user-images.githubusercontent.com/54654681/105621212-2f979500-5e2b-11eb-817e-de158c3cb89e.png)

**System Information (please complete the following information):**
 - OS/Distro: Manjaro

**Additional context**
N/A

**Comment by Zzombiee2361** [comment]
Similar issue with #35 and #75.
Try clearing fontconfig cache
```bash
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
```
If that doesn't work then find fontconfig folder inside snap folder
`find ~/snap/walc/ -name 'fontconfig'`
Then delete that folder and restart WALC

**Comment by Darklight-user** [comment]
I have the same issue but also in the comfirm exit menu. 
![Exit](https://user-images.githubusercontent.com/71706433/107734208-e13b2f00-6d22-11eb-861a-e7d80d393668.png)

**Comment by Zzombiee2361** [comment]
@Darklight-user so did you try my suggestion? Does this also happens with another snap app?

**Comment by Darklight-user** [comment]
I did the above suggestions still the problem persists.

**Comment by Zzombiee2361** [comment]
Well, there's nothing much we can do as this is a snap issue. You can look the discussion here: https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/90. There's a bunch of other workarounds listed there, if you want you could try those one by one and see if it fixes the issue. Or you could just use the AppImage version of WALC
