### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by TERIIHUB** [cstayyab/WALC#108]
Bug exist though work arround was found to solve it.

**Describe the bug**
During 1rst Elementary OS install.
Setting Time Zone to : French Polynesia" seems to - also - set the APP servers to "pf" (our guessing)
So after 1rst reboot following this fresh install: 
**The /etc/apt/sources.list**

contains various lines refereeing to servers such as : 
deb http://pf.archive.ubuntu.com/ubuntu/ bionic main restricted
Further implication : since update is not possible and utilities like "Update Source tool" IS NOT INSTALLED.
There is no way to modify values - that we know of - without diving in the command line + looking for the file that contain the misleading parameter. A negative experience for newcomers !

The Problem is :
All references to (non-existing?!) server "pf." seems to be posing problems to any "sudo apt update" process.
The ref. return error messages, not allowing any update task :(.
We are not sure that those pf.archives path were ever valid someday ?

**WALC Installation Type:** AppImage / Snap

**To Reproduce**
Run fresh install
Choose French Polinesia as your Time zone.
Proceed with install
reboot
OS updating task should be impossible to run.

**Expected behaviour**
Just leave the US servers as a reference since they are closest to all small countries in the Est Pacific.
NZ for the West Pacific side.

**Did you try closing and then opening it back?:** Yes / No
Problem was solved as soon as we did substitute the PF ref values with US ref. values onb all lines.

**Screenshots**
Some APP adding to Elementary becomes impossible

**System Information (please complete the following information):**
 - OS/Distro:
Elementary Os 5.1 HERA.

**Additional context**
*nothing more to add beside, somebody should make sure that all TIME ZONES used worldwide to - eventually - set up
ref in the sources.list files correspond to real depo servers, small country/Islands probably do not offer such feature...:)
THANKS
Terii

**Comment by Zzombiee2361** [comment]
Excuse me but I don't understand the issue. What's the connection with WALC here?

**Comment by TERIIHUB** [comment]
Oops, seems this post went to the wrong ppl. Sorry !
