### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Pasan-Madhubhashana** [cstayyab/WALC#111]
I can't  send custom GIF. Please enable this feature anyway.
![Screenshot from 2021-02-05 15-33-21](https://user-images.githubusercontent.com/76893605/107019971-527d5e00-67c8-11eb-8e21-f07569e5df2e.png)

**Comment by Zzombiee2361** [comment]
It's whatsapp web limitation and it can't be bypassed unfortunately. This app is mostly whatsapp web wrapper, we can't just add features inside whatsapp web itself. As a workaround, send it as a video or send it from your phone.
