### ISSUE TITLE
massive dns queries to web.whatsapp.com

### ISSUE THREAD

**Issue by cryptosteve2** [cstayyab/WALC#12]
There may be a technical reason for this but with WALC I have a single dns query to web.whatsapp.com **every second**. 

With "native" Whatsapp-Web in Firefox and in Chrome there a no such periodic dns queries. 

![walc-dns-queries](https://user-images.githubusercontent.com/6260784/57028061-57e66580-6c3e-11e9-8c8c-0fd73995a790.png)

**Comment by cstayyab** [comment]
This is to check if web.whatsapp.com is accessible (or is internet available), if it is not accessible then the "Offline error" is displayed.

**Comment by cryptosteve2** [comment]
Is it worth to create a feature request to make it configurable?

**Comment by cstayyab** [comment]
Yeah, you may do that here https://feathub.com/cstayyab/WALC/

Please provide the details how you want it to be "configurable"?

**Comment by cryptosteve2** [comment]
not a bug, issue closed
