### ISSUE TITLE
Disable spell check function (flag)

### ISSUE THREAD

**Issue by franzbrevi** [cstayyab/WALC#122]
Hello there. My system language in English but I'm Italian e I write to my friends in Italian. It's annoying to see the system check everything I write.
Thanks in advance.
Franz

![Screenshot from 2021-02-23 15-27-58](https://user-images.githubusercontent.com/40238634/108857872-d23e6180-75eb-11eb-9672-7f4285cce5fa.png)

**Comment by esurharun** [comment]
@cstayyab is there any way to hack built-in chrome to disable that?

**Comment by Zzombiee2361** [comment]
This should be fixed in upcoming release. I added the option to disable spellchecking

**Comment by cstayyab** [comment]
Fixed in #135 (Release 0.2.0)
