### ISSUE TITLE
[Bug Report] Microphone does not work

### ISSUE THREAD

**Issue by christianrocchetti** [cstayyab/WALC#129]
**Describe the bug**
Microphone not seen by the application

**WALC Installation Type:** Snap

**To Reproduce**
1. Go to a chat
2. Click on recording icon

**Did you try closing and then opening it back?:** Yes

**Screenshots**
![image](https://user-images.githubusercontent.com/37518765/114209239-b229ee00-995e-11eb-99bc-93cd6d2f8d7a.png)

**System Information:**
 - OS/Distro: Ubuntu 20.04 LTS and as a KDE display manager

### Update 

I have installed the AppImage version and I don't have this bug

**Comment by cstayyab** [comment]
@christianrocchetti Update to latest release and check this [Frequently Asked Question](https://github.com/cstayyab/WALC/wiki#how-do-i-enable-microphone-and-camera-in-snap-version-of-walc)
