### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by fabriciorodriguesdev** [cstayyab/WALC#133]
**Describe the bug**

**WALC Installation Type:** AppImage / Snap

**To Reproduce**

**Expected behavior**

**Did you try closing and then opening it back?:** Yes / No

**Screenshots**

**System Information (please complete the following information):**
 - OS/Distro:

**Additional context**

Hi Guys,

I'm also having the same problem, my microphone doesn't work on WALC, I reinstalled it, but it didn't work :(
![erro zap](https://user-images.githubusercontent.com/81734030/115969559-da474e80-a513-11eb-8163-eef636d242b0.png)

**Comment by cstayyab** [comment]
Duplicate of #129
