### ISSUE TITLE
doesn't work anymore, outdated chrome UA

### ISSUE THREAD

**Issue by gsantner** [cstayyab/WALC#14]
![grafik](https://user-images.githubusercontent.com/6735650/61937561-a32ebc80-af7e-11e9-83f9-ceaafb508945.png)

**Comment by cstayyab** [comment]
Working fine ... Can you please mention details of your Operating System and Browser Versions  you have installed?

**Closing for now. Reopen IF problem is still there**

**Comment by gsantner** [comment]
ehm WALC bundles a browser, so that doesnt matter.

Ubuntu 18.04.

**Comment by cstayyab** [comment]
> ehm WALC bundles a chromium browser, so that doesnt matter.

I know. I thought may be there is a slightest possibility of interference from other installed ( Chrome/ chromium) browser.

> Ubuntu 18.04
I am using same OS and it's working fine. Can you open Debug Tools from "Window" menu in WALC and send me any Log messages in "Console" Tab?

**Comment by gsantner** [comment]
I had the downloaded version still in downloads folder and started it..worked today. Don't know really why, but it didn't work back then and I tried multiple times.. :smiley:
