### ISSUE TITLE
[Bug Report] Unsupported font face, perhaps.  

### ISSUE THREAD

**Issue by naivomah3** [cstayyab/WALC#142]
**Describe the bug**
I didn't figure out the issue over here. Since a while the exit pop-up is looking like below. 

**WALC Installation Type:** Snap

**To Reproduce**
- Exit pop-up triggered while doing exit

**Did you try closing and then opening it back?:** Yes 

**Screenshots**
![WALC_001](https://user-images.githubusercontent.com/7285775/117197123-19b54b00-adf0-11eb-921e-4b14c4b28f69.png)

**System Information (please complete the following information):**
 - OS/Distro: Ubuntu 20.04

**Comment by cstayyab** [comment]
Are you on the latest Version?

**Comment by naivomah3** [comment]
I guess yes, Version 2.2117.4

**Comment by naivomah3** [comment]
It seems that the issue was solved after uninstalling the snap version and running the AppImage having the same version. Thank you.

**Comment by cstayyab** [comment]
@naivomah3  Just to investigate this issue for future, can you provide your system details as follows:

Desktop Environment you're using: ?
Desktop Environment Version: ?

Also Can you run following commands as provided [here](https://github.com/electron-userland/electron-builder/issues/5217#issuecomment-700707564)  if you encounter the same issue again?

```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by naivomah3** [comment]
Yeah I will, for sure. 
I'm using ubuntu Gnome ver 3.36.5 as DE.

**Comment by c-martinez** [comment]
I ran into the same issue (in Fedora 33). Tried the above commands, but it did not make a difference. I also went for uninstalling snap and using the AppImage.

**Comment by pablopda** [comment]
I have the same issue with fonts. When I run WALC on the terminal I have this warnings
walc
SNAP env is defined, updater is disabled

(walc:34699): Gtk-WARNING **: 14:49:27.211: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(walc:34699): Gtk-WARNING **: 14:49:27.213: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(walc:34699): Gtk-WARNING **: 14:49:27.214: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name

**Comment by martin-wanderer** [comment]
I confirm the issue on Ubuntu 23.04. Walc installed from snap, version 0.2.1, while application itself shows version 2.2323.4
Also confirm messages in terminal about font-feature-settings
Removing font-cache also did not help.
```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```
Installing from AppImage helped, however there's another bug (or feature?): dialog window opens in the background and you need to click on notification to view it.
