### ISSUE TITLE
[Bug Report] WhatsApp funktioniert nur mit Chrome 60+

### ISSUE THREAD

**Issue by Sbahnfreund-Stuttgart** [cstayyab/WALC#146]
This happens after opening the App using the AppImage.
Is this problem known and is there already a solution?
![grafik](https://user-images.githubusercontent.com/58299954/118638091-c4594080-b7d6-11eb-814b-d83bcf824a61.png)

**Comment by Zzombiee2361** [comment]
https://github.com/cstayyab/WALC/issues/138#issuecomment-834193803  
Just read down below, it's supposed to be fixed in upcoming release. But the workaround for now is using WhatsApp web in english

**Comment by Sbahnfreund-Stuttgart** [comment]
Thanks for the answer, I hadn't seen the other thread. Sorry
