### ISSUE TITLE
[Feature Request] Close to tray

### ISSUE THREAD

**Issue by Zzombiee2361** [cstayyab/WALC#15]
And put the number of unread notifications on the tray like what telegram does. This project is great, but imo without this it has no difference than running whatsapp web in app mode using chrome

**Comment by cstayyab** [comment]
I will look into it. Meanwhile PRs are welcomed.

**Comment by cstayyab** [comment]
Added Tray Icon in version 0.1.5 (https://github.com/cstayyab/WALC/releases/tag/v0.1.5)
Number of unread notifications would be added in next minor or revision released. 

Add report this feature request here so it can be in record https://feathub.com/cstayyab/WALC/
Thank you for your suggestions.
Closing for now.

**Comment by Zzombiee2361** [comment]
Nice! Ok I'll put it there

**Comment by Zzombiee2361** [comment]
Update: after trying it out, while it can close to tray, it exit the app when I close the window. Maybe add an option to allow close to tray and add a menu to exit app

**Comment by cstayyab** [comment]
Vote for this feature here:

https://feathub.com/cstayyab/WALC/+2

This issue is only to track the progress an bugs in this issue. Please don't pollute it.
