### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by NPrashanthReddy** [cstayyab/WALC#156]
**Characters in File system are not readable**
The first time downloading the WALC has no issue, but from the next time all the characters are visible as blocks

**WALC Installation Type:**  Snap

**To Reproduce**
1. Go to any chat's downloadable file
2. Click on download
3. See error

**Expected behavior**
The text should be clear to navigate our file system 

**Did you try closing and then opening it back?:**  No

**Screenshots**
![Problem](https://user-images.githubusercontent.com/72489376/124389661-c1be9600-dd05-11eb-95a9-a38e02d27226.png)

**System Information (please complete the following information):**
 - OS/Distro: Linux/Ubuntu 20.04.2 LTS

**Comment by tubbadu** [comment]
I think it's a snap-installed apps problem, most of my apps installed this way gives me this error, like walc and Discord...
use the appimage, it works perfectly

**Comment by YoungFellow-le** [comment]
I got the same problem when installing WALC using snap, however I solved it by running it from the .AppImage, which you can download from here.
Once you've run it and logged in, go to the WALC icon and look through the settings, and you'll find the option which allows you to add WALC to your system menu.

**Comment by NPrashanthReddy** [comment]
Thank you for your suggestion it worked that way, but I wonder why it happened with the snap image
