### ISSUE TITLE
Alt-Shift doesn't change the language layout

### ISSUE THREAD

**Issue by ZeroBit** [cstayyab/WALC#16]
Hi!

Many people, including me, use Alt-Shift as a language layout switcher. In this app it opens menu and does not allow switching languages. Please, fix it.

**Comment by cstayyab** [comment]
It depends on your OS. Checkout this StackOverflow link for more details:
[Ubuntu 17.10 and later: can't change the input switching shortcut to alt+shift](https://askubuntu.com/questions/967364/ubuntu-17-10-and-later-cant-change-the-input-switching-shortcut-to-altshift)

I am closing this issues as it is not relevant to this repository. If you think it is relevant please reopen it and provide more details about your OS, distro and WALC version.
