### ISSUE TITLE
[Bug Report] Tray Menu not being displayed in Snap Version

### ISSUE THREAD

**Issue by cstayyab** [cstayyab/WALC#18]
**Describe the bug**
Snap Version does not display the Tray Context menu on right click.

**WALC Installation Type**: Snap

**To Reproduce**
1. Install WALC using snap
2. Open WALC
3. Right-Click Tray Icon

**Expected behavior**
A Tray Context Menu should be display

**Did you try closing and then opening it back?:** Yes

**Screenshots**
Here is the AppImage menu that is being displayed in AppImage Version but not in Snap Version
![WALC Menu in AppImage Version](https://imgur.com/download/VvAkOmR)

**System Information**
 - OS/Distro:
 - Browsers Installed on your system: Firefox
 - Node Version(node --version): v12.16.1
 - NPM version (npm --version): 6.13.4

**Comment by AlwaysBeCalm** [comment]
Hi @cstayyab 
I'm reporting a bug in walc, even though I've removed walc from my applications, the tray icon is still exists and it counted as a process in the system
see :point_down: 
![image](https://user-images.githubusercontent.com/54927528/82117022-4a7f1900-9776-11ea-8ca2-a1c4b7228c93.png)

it gone when I killed the process (the first ps in the image :point_up: )

**Comment by cstayyab** [comment]
Hi @AlwaysBeCalm ! Thanks for reporting the issue. Please create a new Issue from the issues tab and provided the information required such as How to reproduce this bug and your OS Details. Also can you consistently reproduce this bug? Did double clicking the tray icon displays WALC?

Thanks.

**Comment by mhatvan** [comment]
@cstayyab I am taking a look at this, what is the best way to debug the snap locally?

I am able to run the `dist` script but when trying to run the snap locally, I encounter this when I try to start the snap through the terminal:
```
Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory
``` 

I guess this is related to the `dist` script output:

```
prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.27.0/sharp-v0.27.0-electron-v85-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=11.2.1 runtime=electron arch=x64 libc= platform=linux)
```

If you can tell me how to solve this, I can investigate the issue further.
