### ISSUE TITLE
Open links in default browser

### ISSUE THREAD

**Issue by Slomo17** [cstayyab/WALC#2]
First of all, thanks, finally a working whatsapp app again. But i noticed when you click a link, it opens in an extra window instead of the OS's default browser. I think opening it in the default browser would be better.

**Comment by cstayyab** [comment]
Yes, I also noticed this issue, I am adding it to my todo list. I would appreciate if someone or you can work on it and generate a pull request. If you want I can assign it to you.

**Comment by Slomo17** [comment]
Sorry, i am not a developer, i think i won't be much help :(

**Comment by cstayyab** [comment]
No problem. I will look into it myself. 😄

**Comment by cstayyab** [comment]
This has been added to the newest version. Please check new release [here](https://github.com/cstayyab/WALC/releases/tag/v0.1.1)

Thanks for contributing by point it out.
