### ISSUE TITLE
[Bug Report] Problem with serviceworker.js of WhatsApp Web

### ISSUE THREAD

**Issue by odd22** [cstayyab/WALC#21]
**Describe the bug**
After the initial run, Walc always request to upgrade to latest Google Chrome version

**WALC Installation Type:** AppImage / Snap

Both AppImage and Snap package give the same error after the initial run

**To Reproduce**
1. Install walc with AppImage or Snap
2. Run walc and scan the QR code to initialize walc with your What's App account
3. Close walc
4. Re-launch walc and you get the web page requesting to upgrade to latest Google Chrome instead of starting the What'sApp page

**Expected behavior**
Start What's App web page

**Did you try closing and then opening it back?:** Yes / No
Yes. Once you felt into the Google Chrome upgrade, you never get back the What's App web page

**Screenshots**
![image](https://user-images.githubusercontent.com/7986216/77942354-c7842b00-72bb-11ea-9dcf-befe36e41c75.png)

**System Information (please complete the following information):**
 - OS/Distro: Ubuntu 18.04 LTS
 - Browsers Installed on your system: Firefox, Chromium, Google-Chrome, all up to date through apt update / apt upgrade
 - Node Version(node --version): v8.10.0
 - NPM version (npm --version): not install

**Comment by cstayyab** [comment]
Hey @odd22  Thanks for reporting this. Actually the problem is very rare and is not due to a problem in WALC. Usually this problem is solved by clearing the cache inside WALC. 

Please follow the following steps to see if it solves the issue:
1. Open WALC and select "Debug" Tools from "Window" Menu
2. Select "Application" Tab from "Debug Tools" Window
3. From the sidebar that appears in "Debug Tools" Select "Clear Storage"
4. Check All the check boxes from the main window of "Debug Tools" and Click on "Clear site data"
5. Restart WALC

**Comment by cstayyab** [comment]
I still can't exactly figure out what causes this issue because it occurs very rarely so if anyone can help, it would be great.

**Comment by odd22** [comment]
@cstayyab Thanks for you help. It is a safer way to operate that mine (remove the snap/walc directory in my home folder).
Regarding how to reproduce the problem, I've the feeling that this take after the application is disconnected for a certain period of time. Closing walc and re-open it within a minute works. The problem occurs if I close walc for a long period of time e.g. closing it the evening and re-open it the morning. There is perhaps a timeout regarding the QR-Code you scan, because, when it failed, I need to re-scan a new QR-code (i.e. re-initialize walc).

I'll close walc this evening and try you solution tomorrow morning and let you know what's happen.

**Comment by odd22** [comment]
@cstayyab Finally, since one week, I never failed into the mention bug. Last time it occurs, I follow your recommendation, clear the cache and re-scan a new QR code. Now, walc is stable and reconnect fine each time I disconnect, stop or wake-up my computer after being in sleep mode.

I think you could close this bug.

**Comment by RDKclick** [comment]
Is there a solution to this problem?
