### ISSUE TITLE
Enable Dark mode

### ISSUE THREAD

**Issue by mac-linux-free** [cstayyab/WALC#22]
Please enable Dark Mode

**WALC Installation Type:** AppImage

**Comment by cstayyab** [comment]
Dark Mode is not yet available for WhatsApp Web. Hence this does not fall under the category of Bug. Dark Mode will be available in WALC as soon as it gets available in WhatsApp Web. 

Reference: https://wabetainfo.com/whatsapp-is-developing-a-dark-theme-for-whatsapp-web-and-desktop/
