### ISSUE TITLE
[Feature Request] Display notification when either PC or phone is disconnected

### ISSUE THREAD

**Issue by Zzombiee2361** [cstayyab/WALC#25]
**Feathub Feature Link:** https://feathub.com/cstayyab/WALC/+5

**Is your feature request related to a problem? Please describe.**
Sometimes when my phone got disconnected like when wifi goes out of range and data is off or when whatsapp is killed by battery saver, I didn't realize and missed many important messages.

**Describe the solution you'd like**
It would be cool to be notified when it happens so I don't miss any messages.

**Describe alternatives you've considered**

**Additional context**
![I would like to be notified when this happens](https://user-images.githubusercontent.com/37852137/80484182-7c743b00-8981-11ea-8e2d-5a60723a6b1d.png)

---
**To view all feature requests and to vote for your favorite ones visit https://feathub.com/cstayyab/WALC This will help in determining which feature needs to be implemented first**

**Comment by cstayyab** [comment]
WALC now shows a notification if PC goes offline or WhatsApp Web Server is not accessible due to some reason. Same for mobile still needs to be done.

**Comment by Zzombiee2361** [comment]
I think it's better to display the custom offline page **only** when the page can't load. If the page is already loaded and the network goes offline, let the page be. It's simpler and faster to let whatsapp handle it on its own. Reloading the page takes more time than simply reconnecting.

**Comment by cstayyab** [comment]
@Zzombiee2361 I like your suggestion. I will implement it.

**Comment by Zzombiee2361** [comment]
Bump! Are you currently working on this? I'd like to try implementing this myself if you're not.

Also, the custom offline page is blindly bright when dark mode is enabled, you might wanna change that.

**Comment by cstayyab** [comment]
I am not currently working on this due to some constraints on my side. You are free to give it a try. Draft a pull request an I will attach this issue to that PR.

Here is a sample you can use after finding the CSS selector that WhatsApp is using to show the "Phone not connected" banner:
```
const KEEP_PHONE_CONNECTED_IMG_SELECTOR = '[data-asset-intro-image="true"]';
await page.waitForSelector(KEEP_PHONE_CONNECTED_IMG_SELECTOR, { timeout: 0 });
```

**Comment by AlwaysBeCalm** [comment]
Hi @cstayyab 

The icon on the tray menu is showing that I have new messages even though I've muted all me chats, while on web.whatsapp it doesn't show notifications for muted chats.

![muted 2](https://user-images.githubusercontent.com/54927528/82175678-31dd4300-98dd-11ea-9d12-28a4a5007847.png)

this image is when I unmuted one of my chats... :point_down: 

![unmuted 1](https://user-images.githubusercontent.com/54927528/82175720-59cca680-98dd-11ea-9f2b-55e2f1cffc16.png)

it's supposed to show notifications only for unmuted chats, right?

thanks for your time :rose: :rose:

**Comment by Zzombiee2361** [comment]
Hello @AlwaysBeCalm 

I implemented this feature and it is intended that way, kinda like telegram desktop does, although telegram tray badge is colored gray when there's unread only on muted chats. Do you want similar behavior or just not count the muted chats?

Btw this is not a relevant issue, you should open a new issue or comment on #26

**Comment by AlwaysBeCalm** [comment]
@Zzombiee2361 
I think it's best to be optional like Telegram.

Thanks
