### ISSUE TITLE
[Bug Report] Update broke AppImage desktop integration

### ISSUE THREAD

**Issue by Zzombiee2361** [cstayyab/WALC#33]
**Describe the bug**
Every update, the AppImage file name changes thus breaking desktop integration or other link

**WALC Installation Type:** AppImage

**To Reproduce**
1. Update WALC
2. Desktop file no longer works

**Expected behavior**
Better to just name the file "WALC.AppImage" for future updates

**Comment by cstayyab** [comment]
I just checked it on my system and it's working fine. Can you provide more details or any error?

> Better to just name the file "WALC.AppImage" for future updates

I will update the AppImage name in next next version.

**Comment by Zzombiee2361** [comment]
![image](https://user-images.githubusercontent.com/37852137/82123083-9905d500-97c1-11ea-8b86-740045fb9aa4.png)
This is what happens when I launch the menu entry after update. Also I made custom autostart entry on plasma systemsettings, and that also broke after update.

**Comment by cstayyab** [comment]
According to what I have tested the Update is done on the same file but file is not renamed so that's why this error occurs. If I rename previous and new release to same name i.e. "WALC" then it should not break. but this is a workaround what if user himself renames  the AppImage after download?

**Comment by Zzombiee2361** [comment]
Good point. Then the update shouldn't change the filename, just use the current AppImage filename

**Comment by Zzombiee2361** [comment]
Apparently, [this has been fixed](https://github.com/electron-userland/electron-builder/issues/2964). I just have to remove the version from the file name.
