### ISSUE TITLE
[Bug Report] Unread badge counts muted groups

### ISSUE THREAD

**Issue by SergioVJr** [cstayyab/WALC#36]
**Describe the bug**
If a muted group has unread messages, the tray icon badge still counts them.

**WALC Installation Type:** Snap

**To Reproduce**
1. Mute a group
2. Receive a message in said group
3. Observe increased number in tray icon badge

**Expected behavior**
The tray icon badge to only count unmuted chats to its total

**Did you try closing and then opening it back?:** Yes

**System Information (please complete the following information):**
 - OS/Distro: Kubuntu 20.04

**Comment by cstayyab** [comment]
Quoting @Zzombiee2361 Here:

> Hello @AlwaysBeCalm
> 
> I  implemented this feature and it is intended that way, kinda like telegram desktop does, although telegram tray badge is colored gray when there's unread only on muted chats. Do you want similar behavior or just not count the muted chats?

**Comment by SergioVJr** [comment]
Telegram Desktop has a checkbox exactly about this called "Include muted chats in unread count" (under Notifications, Badge counter). It'd be perfect if that option was available here as well.

**Comment by SergioVJr** [comment]
But if it's intended, I guess I'll close it and reopen as a feature request.
