### ISSUE TITLE
[Bug Report] repeated and frequent disconnects

### ISSUE THREAD

**Issue by seanj2** [cstayyab/WALC#41]
**Describe the bug**

System repeatedly looses connection and reconnects

**WALC Installation Type:** AppImage / Snap
SNAP

**To Reproduce**
Steps to reproduce the behavior: occurs frequently during normal operations

**Expected behavior**

**Did you try closing and then opening it back?:** Yes / No
Yes
**Screenshots**
![image](https://user-images.githubusercontent.com/58517674/83419136-970f5900-a3f2-11ea-89fe-966c8509190c.png)

**System Information (please complete the following information):**
 - OS/Distro:
Ubuntu 20.04
**Additional context**

**Comment by Zzombiee2361** [comment]
This is a known issue in this version. This #38 pull request should fix that along with many other changes. Hey @cstayyab, when will you release the update?

**Comment by cstayyab** [comment]
>  Hey @cstayyab, when will you release the update?

I am planning to add more features before releasing version 0.2.0

**Comment by Zzombiee2361** [comment]
> I am planning to add more features

Any time now...
> releasing version 0.2.0

Why isn't it 0.1.10?

**Comment by cstayyab** [comment]
> Why isn't it 0.1.10?

Yeah I can do that and jump to 0.2.0 later

Okay I will release an upgrade in a day or two

> Any time now... What is it anyway?

Was working completing Auto Replies feature. It a big feature so it is taking time.

**Comment by Zzombiee2361** [comment]
@seanj2 please try the new version and see if it already fixed. If it is then please close this issue

**Comment by cstayyab** [comment]
Closing as inactive. If you are still facing this problem please start a new Discussion in [Troubleshooting](https://github.com/cstayyab/WALC/discussions?discussions_q=category%3ATroubleshooting) Section
