### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by jrr45** [cstayyab/WALC#45]
**Describe the bug**
Snap fails to launch and silently exits, no output to the terminal if launched using that. This seems to happen only if the program is terminated by a shutdown without exiting the app first. Reinstalling the snap fixes everything.

**WALC Installation Type:** Snap

**Did you try closing and then opening it back?:** Yes 

**System Information (please complete the following information):**
 - OS/Distro: Kubuntu 20.04

**Comment by Zzombiee2361** [comment]
Are you sure it exits? Nowhere to be seen in process list? Or is it just tray icon not displayed and you happen to enable Start Hidden option so WALC seems to just vanish?

**Comment by jrr45** [comment]
There isn't anything resembling WALC in system monitor or top from what I can tell. The terminal command exits immediately without seeming to start anything. I haven't changed any settings after reinstalling it.
