### ISSUE TITLE
[Bug Report] Language problem

### ISSUE THREAD

**Issue by HosseinKurd** [cstayyab/WALC#48]
it shows an unknown language alphabet.

![Screenshot from 2020-06-21 15-03-19](https://user-images.githubusercontent.com/7655247/85222464-6eb2c300-b3d0-11ea-9623-3d5e1c42e318.png)

**Comment by Zzombiee2361** [comment]
I'm going to guess, you're using snap. There's a similar issue here: #35

**Comment by cstayyab** [comment]
Closing as Inactive. Please start a new Discussion in [Troubleshooting](https://github.com/cstayyab/WALC/discussions?discussions_q=category%3ATroubleshooting) Section if you are still facing this issue.
