### ISSUE TITLE
[Bug Report] Tray icon does not show new messages

### ISSUE THREAD

**Issue by lashkevi** [cstayyab/WALC#49]
**Describe the bug**
When I first installed WALC, a red round mark with the number of new messages appeared on the tray icon. Then this behavior stopped working. The tray icon remains unchanged (green), when new messages come (though I can here a sound, when it comes, if I am near the computer).

**WALC Installation Type:** AppImage

**To Reproduce**
1. Start WALC and connect it to Whatsapp Web.
2. Wait for new messages and look at the tray icon.
3. See that the tray icon is unchanged.

**Expected behavior**
A red circle with the number on new messages (or threads?) should appear.

**Did you try closing and then opening it back?:** Yes

**System Information (please complete the following information):**
 - OS/Distro: OpenSUSE 15.1

**Comment by Zzombiee2361** [comment]
This happens due to change in whatsapp. This pull reqest #47 should fix that.

**Comment by cstayyab** [comment]
Closing as Pull request #47 has been merged and it should fix the issue.
