### ISSUE TITLE
with due respect....BORING!!!

### ISSUE THREAD

**Issue by ReaperN0v** [cstayyab/WALC#5]
I would recommend to make the client compatible via python and pxssh and design a combination of ssh and beautiful soup to interact with the web and make a direct connection with WhatsApp for linux...also use json .

Cheers!
feel free to check out my latest custom kNN algorithm !

**Comment by cstayyab** [comment]
With due respect, the repo is fulfilling the purpose, although it requires some enhancements.
Also, this is not an advertisement board for other repos.

**closing because off-topic**
