### ISSUE TITLE
[Feature Request] Please Provide notification alert in new masage arrived..thanks 

### ISSUE THREAD

**Issue by charitha-pro** [cstayyab/WALC#58]
**Feathub Feature Link:** Please request this feature at https://feathub.com/cstayyab/WALC too. This issue will be used to track this feature only. Requests that are submitted at given URL will be entertained first according to number of votes on that feature.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

---
**To view all feature requests and to vote for your favorite ones visit https://feathub.com/cstayyab/WALC This will help in determining which feature needs to be implemented first**

**Comment by Zzombiee2361** [comment]
What do you mean? WALC does send message notification. If it doesn't then you should file a bug report and actually fill the issue template.

**Comment by charitha-pro** [comment]
thanks for replying i will try again...my notification is not working i think.

**Comment by Zzombiee2361** [comment]
Please clarify your issue. If it does still exists, I will reopen.
