### ISSUE TITLE
WhatsApp works with Google Chrome 36+

### ISSUE THREAD

**Issue by m2ura** [cstayyab/WALC#6]
hi,

I get this, and it keeps on telling me "WhatsApp works with Google Chrome 36+
To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera." while my Chrome and Firefox are up to date, I made an upgrade on my parrot and installed the latest Chrome

Gtk-Message: 12:53:09.447: Failed to load module "atk-bridge"

**Comment by kominoshja** [comment]
Me too

**Comment by guygrinberger** [comment]
same

**Comment by cstayyab** [comment]
Solved by #7 
Thanks to # @Carpediem94

**Comment by cstayyab** [comment]
Reopening because issue is still there....

**Comment by cstayyab** [comment]
Here is a solution:

**Clear WhatsApp cache**

It could be that you need to manually clear your WhatsApp cache before it starts to work.
To do that:

    Open WhatsApp Linux Client (WALC)
    Open the Service Developer Tools (Ctrl+Shift+Alt+I)
    In the Developer Tools, go to "Application"
    Go to "Clear storage" and select
        Unregister service workers
        IndexDB
        Web SQL
        Cache Storage
        Application Cache
    Close and Reopen WALC
