### ISSUE TITLE
[Bug Report] WALC doesn't recognize microphone

### ISSUE THREAD

**Issue by ubuntuman9** [cstayyab/WALC#63]
mi walc dont reconice mi microphone

**Comment by cstayyab** [comment]
Which version of WALC areyou using? Snap or AppImage? Which Linux Distro are you using? its Version etc? Please provide these details.

**Comment by omaregb** [comment]
Hi, I have the same problem. The mic is not detected. I'm in Manjaro and this is the Snap version. Not sure if it's relevant, but it also didn't work on Whatsapp web on chrome initially, but this was because Chrome automatically detects the wrong device as mic, selecting it manually in Chrome settings fixed it in the browser.

**Comment by cstayyab** [comment]
@omaregb & @ubuntuman9  This might just be a permission issue. Can you please run this in the terminal and tell me about the results:

`sudo snap connect walc:audio-record :audio-record`

The above command should fix the issue.

**Comment by omaregb** [comment]
I get this : 

`error: snap "walc" has no plug named "audio-record"
`

**Comment by cstayyab** [comment]
@omaregb can you post the output of 

`sudo snap connections walc`

**Comment by omaregb** [comment]
sure, this is it. 
`Interface                 Plug                  Slot                             Notes
audio-playback            walc:audio-playback   :audio-playback                  -
browser-support           walc:browser-support  :browser-support                 -
camera                    walc:camera           -                                -
content[gnome-3-28-1804]  walc:gnome-3-28-1804  gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     walc:gtk-3-themes     gtk-common-themes:gtk-3-themes   -
content[icon-themes]      walc:icon-themes      gtk-common-themes:icon-themes    -
content[sound-themes]     walc:sound-themes     gtk-common-themes:sound-themes   -
desktop                   walc:desktop          :desktop                         -
desktop-legacy            walc:desktop-legacy   :desktop-legacy                  -
gsettings                 walc:gsettings        :gsettings                       -
home                      walc:home             :home                            -
network                   walc:network          :network                         -
opengl                    walc:opengl           :opengl                          -
pulseaudio                walc:pulseaudio       -                                -
unity7                    walc:unity7           :unity7                          -
wayland                   walc:wayland          :wayland                         -
x11                       walc:x11              :x11                             -
`

**Comment by cstayyab** [comment]
Okay, I think I have found the problem. Some of the snap interfaces have been deprecated and updated by others so I will have to replace it with new ones. I hope to fix it over the weekend.

**Comment by cstayyab** [comment]
Electron is not auto-connecting `pulseaudio` interface with the WALC. Please run the following command to get the Microphone working:

```sh
sudo snap connect walc:pulseaudio :pulseaudio
```

CC: @omaregb @ubuntuman9

**Comment by omaregb** [comment]
I did this. the command does not return any error messages but after restarting walc microphone is still not recognized
