### ISSUE TITLE
[Bug Report] Error with ticks

### ISSUE THREAD

**Issue by yalin** [cstayyab/WALC#70]
**Describe the bug**
After the new update, ticks work wrong. In the WALC application, it doesn't show message delivered ticks (any tick, one or two tick) but when I open my phone, it shows the message had arrived with ticks. Then I do alt+tab and change to another window in the OS and then when I come back to WALC, ticks are there sometimes (not always). They don't refresh themselves while the WALC window is open.

**WALC Installation Type:** AppImage / Snap
Snap Version: 0.1.11(17)
OS: Ubuntu 20.04.1 LTS

**To Reproduce**
1. Open WALC
2. Go to a conversation window
3. Write a message
4. See error; tick does not appear/refresh by itself (but at phone ticks appear)
5. Press Alt+tab
6. Then again go back to WALC window
7. Ticks appear sometimes / sometimes stays same(if delivered)

**Expected behavior**
Ticks should refresh itself while the window is open, when the message has delivered.

**Did you try closing and then opening it back?:** Yes / No
Yes

**Screenshots**

![image](https://user-images.githubusercontent.com/652545/95744482-f0737880-0c6d-11eb-8999-15fad43c1861.png)
It stays like this even the message actually delivered.

**System Information (please complete the following information):**
 - OS/Distro:
OS: Ubuntu 20.04.1 LTS

**Additional context**
Bug started after the last update.

**Comment by yalin** [comment]
I also noticed, when we switch windows between other whatsapp chats on the left menu, ticks refresh and appears but they do not automatically by itself while the active window stays open.

**Comment by Zzombiee2361** [comment]
I can confirm this issue but is this WALC specific or is it also happening in whatsapp web?

**Comment by yalin** [comment]
I haven't tried since you mentioned and I just looked at WhatsApp web (using Chromium browser Version 85.0.4183.121 (Official Build) snap (64-bit))  and it works with WhatsApp web, ticks work properly (as soon as I enter my message, it changes to tick when it arrives)

_Thank you for reminding WhatsApp web._

**Comment by Zzombiee2361** [comment]
I bet it's the whatsapp-web.js, or if it's not working I could try updating electron. But the problem is, I can't release the update and the maintainer, @cstayyab isn't responding my emails. If he's still not responding maybe I'll release it on my fork.

**Comment by Zzombiee2361** [comment]
Also, I can't consistently reproduce the issue. It happens rarely and if it does I can just reload (Window > Reload Without Cache) and the issue fixes itself. This could be a problem from whatsapp web itself.

**Comment by cstayyab** [comment]
> 
> 
> I bet it's the whatsapp-web.js, or if it's not working I could try updating electron. But the problem is, I can't release the update and the maintainer, @cstayyab isn't responding my emails. If he's still not responding maybe I'll release it on my fork.

I have uploaded the AppImage and Sent you an email regarding SnapStore.

**Comment by yalin** [comment]
> Also, I can't consistently reproduce the issue. It happens rarely and if it does I can just reload (Window > Reload Without Cache) and the issue fixes itself. This could be a problem from whatsapp web itself.

Window > Reload Without Cache worked temporarily. Thanks for the solution.

**Comment by Zzombiee2361** [comment]
@yalin is this still happening now? I noticed that it doesn't happen anymore on my system

**Comment by browser-bug** [comment]
@Zzombiee2361 Just checked and it's fixed for me. Sup

**Comment by yalin** [comment]
@Zzombiee2361 no, not anymore, it fixed. Thank you. Closing the topic.
