### ISSUE TITLE
Font displayed as blocks

### ISSUE THREAD

**Issue by abhinavms** [cstayyab/WALC#75]
**Describe the bug**
The texts in chat interface is normal. But when i try to close the app or attach a file, the text in the dialog box are displayed as blocks / empty rectangles.

**WALC Installation Type:** Snap

**To Reproduce**
1. Install using snap
2. Attach a image

**Did you try closing and then opening it back?:** Yes

**Things I did to try to fix**
1. Deleting fontconfig cache directory in home [rm ~/.cache/fontconfig/*]
2. Deleting system cache [rm -f /var/cache/fontconfig/*]
3. fc-cache -r
4. Reinstalling the snap

**Screenshots**
![](https://i.imgur.com/malYZ0a.png)
![](https://i.imgur.com/Thww1WJ.png)

**System Information**
 - OS/Distro: Manjaro 20.2
- Kernel: 5.8.18-1
- DE: Plasma 5.20.2

**Comment by Zzombiee2361** [comment]
What font and language you use?

**Comment by abhinavms** [comment]
> What font and language you use?
Font is Noto Sans and language is English.

**Comment by Zzombiee2361** [comment]
First find fontconfig folder inside snap folder  
`find ~/snap/walc/ -name 'fontconfig'`  
Then delete that folder and restart WALC

**Comment by abhinavms** [comment]
I tired that now, but didn't work.

I checked the log and it was showing a message 
`Gtk-Message: 09:09:46.705: GtkDialog mapped without a transient parent. This is discouraged.`

Could this be the issue ?

**Comment by Zzombiee2361** [comment]
Nope. I've run out of idea on how to debug this. It's clearly a snap issue

**Comment by abhinavms** [comment]
Okay. I'll check with snap then. Thanks for helping 😁

**Comment by srikanth-kandi** [comment]
> First find fontconfig folder inside snap folder `find ~/snap/walc/ -name 'fontconfig'` Then delete that folder and restart WALC

this worked for me
