### ISSUE TITLE
[Feature Request] crtl + q should not close the app

### ISSUE THREAD

**Issue by ggrrll** [cstayyab/WALC#76]
**Feathub Feature Link:** 
![feathub_bug](https://user-images.githubusercontent.com/15370425/98232829-6feb2380-1f5e-11eb-8e50-3839a26ab297.png)

**Is your feature request related to a problem? Please describe.**
`crtl` + `q`  shortcut closes the app entirely
 

**Describe the solution you'd like** 
I would like that the shortcut closes only the window, leaving the app open (icon in the system tray)
maybe adding another shortcut for quitting the app, e.g.:

* `crtl` + `q`   + `q`  
* `crtl` +  `shift` + `q`  

**Additional context**
currently on
* ubuntu 20.04
* cinnamon 4.4.8

Thanks :)

**Comment by Zzombiee2361** [comment]
What's wrong with Alt+F4? Why should I add a shortcut to close a window when a global universal shortcut already exists?

**Comment by Zzombiee2361** [comment]
Also, that would break other people's workflow. After an update suddenly they found out that Ctrl+Q doesn't actually close the app, then they file a new bug report on an intended feature. They could even argue that this is stupid and I should revert the change

**Comment by ggrrll** [comment]
ok sorry, 

I don't use  `Alt` + `F4` as I find it a bit uncomfortable 
(never mind, I don't wanna open now a 'shortcut war' now :sweat_smile: )  

(anyway, just fyi,  in WhatsDesk `Ctrl` + `Q` leaves the app open...so, there are enough apps for all tastes :) )
