### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by jneusse** [cstayyab/WALC#82]
**Describe the bug**

I cant use my microphone... seems its not detected by the app

**WALC Installation Type:** AppImage / Snap

**To Reproduce**

**Expected behavior**

**Did you try closing and then opening it back?:** Yes / No

**Screenshots**

**System Information (please complete the following information):**
 - OS/Distro:

**Additional context**

**Comment by cstayyab** [comment]
Closing as Duplicate of #63
