### ISSUE TITLE
[Bug Report] No badge counter on tray icon

### ISSUE THREAD

**Issue by Josefovo** [cstayyab/WALC#90]
There is no badge counter on tray icon, even if there are some unread messages. The system notification appears and disappears normally, but no badge counter shows.

WALC 0.1.11
Installation Type: Snap
Snap Version:0.1.11(17)OS: Ubuntu 20.04.1 LTS
actually, it's Kubuntu...

It behaves that way from the installations few weeks ago. Other apps have their badges.

![Screenshot_WALC](https://user-images.githubusercontent.com/40386121/102686365-87692d80-41e7-11eb-822d-043d97be7700.png)

**Comment by bkmo** [comment]
I too have lost my counter. I thought it may have been after a Whatsapp update.

**Comment by PronElle** [comment]
I've lost mine either. I believe it's whatsapp web's fault.

**Comment by cstayyab** [comment]
I have checked the console message which says:
```
electron/js2c/renderer_init.js:91 Unable to load preload script
```
As this feature is dependent on preload.js so that's why it's not working

**Comment by hiddenman** [comment]
Hi,

The same issue here. Any idea how to fix this?
Thank you.
