### ISSUE TITLE
WhatsApp Lock

### ISSUE THREAD

**Issue by y16032001s** [cstayyab/WALC#92]
## Please use "Feature Requests" Category of [WALC Discussion Board](https://github.com/cstayyab/WALC/discussions?discussions_q=category%3A%22Feature+Requests%22) for Feature Requests.
plz add an whatsapp lock with a timer for auto lock if away

**Comment by cstayyab** [comment]
Hi @y16032001s! Thank you for helping in improving WALC. Before WALC contributors can implement any new features, its details must be cleared and written in detail for later testing of the feature and reference.

Please explain the feature in detail by editing the description of the issue or start a discussion [here](https://github.com/cstayyab/WALC/discussions?discussions_q=category%3A%22Feature+Requests%22) so the details can be refined and then implemented.

**Comment by cstayyab** [comment]
Continuing this on Discussion Board #99
